- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    base_image: debian:stretch
    container_name: jenkins-agent-builder
    image_namespace: nexus.cci-dev.pl/repository/docker
    image_name: jenkins-agent
    java_version: 8u181-b13-2~deb9u1
    java_home: /usr/lib/jvm/java-8-openjdk-amd64
    jenkins_home: /opt/jenkins
    maven_version: 3.6.0
    maven_home: "/opt/maven/apache-maven-{{ maven_version }}"

  roles:
    - name: base
    - name: content
      delegate_to: '{{ container_name }}'
    - name: push
