- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    base_image: debian:stretch
    container_name: jenkins-agent-builder
    image_namespace: nexus.cci-dev.pl/repository/docker
    image_name: jenkins-agent-3

  pre_tasks:
    - name: Make the latest version of the base image available locally
      docker_image:
        name: '{{ base_image }}'
        force: yes

    - name: Create the Docker container
      docker_container:
        image: '{{ base_image }}'
        name: '{{ container_name }}'
        command: sleep infinity

    - name: Add the newly created container to the inventory
      add_host:
        hostname: '{{ container_name }}'
        ansible_connection: docker

    - name: Ensure Python is installed
      raw: >
        apt-get update &&
        apt-get install -y --no-install-recommends python3
      delegate_to: '{{ container_name }}'

    - name: Gather facts inside the container
      setup:
      delegate_to: '{{ container_name }}'

  roles:
    - name: agent
      delegate_to: '{{ container_name }}'

  post_tasks:
    - name: Clean up the container
      shell: >
        apt-get remove --purge -y python &&
        rm -rf /var/lib/apt/lists/*
      delegate_to: '{{ container_name }}'
      args:
        warn: no

    - name: Commit the container
      command: >
        docker commit
        -c 'WORKDIR {{ jenkins_agent_home }}'
        -c 'ENV JAVA_HOME={{ java_open_jdk_home }}'
        -c 'ENV M2_HOME={{ maven_home }}'
        -c 'ENV MAVEN_HOME={{ maven_home }}'
        -c 'ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:{{ maven_home }}/bin'
        -c 'EXPOSE 22'
        -c 'ENTRYPOINT ["/usr/local/bin/setup-all"]'
        {{ container_name }} {{ image_namespace }}/{{ image_name }}

    - name: Remove the container
      docker_container:
        name: '{{ container_name }}'
        state: absent
