- name: Ansible | install pip tools
  apt:
    name: python3-pip
    state: present
    update_cache: true

- name: Ansible | link pip3 to pip
  file:
    src: "{{ java_home }}"
    dest: /usr/lib/jvm/default-java
    force: true
    state: link

- name: Ansible | install pip tools
  pip:
    executable: /usr/bin/pip3
    name:
      - ansible

- name: Maven | main directory
  file:
    path: /var/log/ansible
    state: directory
    owner: jenkins
    group: jenkins
