- name: Docker | add apt signing key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Docker | add repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
    state: present

- name: Docker | install
  apt:
    name: "docker-ce"
    update_cache: yes
    state: latest
