- name: Maven | main directory
  file:
    path: /opt/maven
    state: directory

- name: Maven | download and unarchive maven
  unarchive:
    src: "http://www.apache.org/dist/maven/maven-3/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz"
    dest: /opt/maven
    copy: no
