- name: Packages | install
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - git
    - apt-transport-https
    - ca-certificates
    - wget
    - software-properties-common
    - gnupg2
    - curl
