- name: Commit the container
  command: >
    docker commit
    -c 'WORKDIR {{ jenkins_home }}'
    -c 'ENV JAVA_HOME={{ java_home }}'
    -c 'ENV M2_HOME={{ maven_home }}'
    -c 'ENV MAVEN_HOME={{ maven_home }}'
    -c 'ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:{{ maven_home }}/bin'
    -c 'EXPOSE 22'
    -c 'ENTRYPOINT ["/usr/local/bin/setup-all"]'
    {{ container_name }} {{ image_namespace }}/{{ image_name }}:{{ image_tag }}

- name: Add tag latest to image
  docker_image:
    name: "{{ image_namespace }}/{{ image_name }}:{{ image_tag }}"
    repository: "{{ image_namespace }}/{{ image_name }}:latest"

- name: Log into private registry and force re-authorization
  docker_login:
    registry: nexus.cci-dev.pl
    username: "{{ nexus_user }}"
    password: "{{ nexus_password }}"
    reauthorize: yes
  tags:
    - push

- name: Build an image and push it to a private repo
  docker_image:
    name: "{{ image_namespace }}/{{ image_name }}"
    push: yes
    tag: "{{ item }}"
  with_items:
    - "{{ image_tag }}"
    - latest
  tags:
    - push

- name: Remove the container
  docker_container:
    name: '{{ container_name }}'
    state: absent
