- name: Post | commit the container
  command: >
    docker commit
    -c 'WORKDIR {{ jenkins_home }}'
    -c 'ENV JAVA_HOME={{ java_home }}'
    -c 'ENV M2_HOME={{ maven_home }}'
    -c 'ENV MAVEN_HOME={{ maven_home }}'
    -c 'ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:{{ maven_home }}/bin'
    -c 'ENV JENKINS_AGENT_HOME={{ jenkins_home }}'
    -c 'EXPOSE 22'
    -c 'ENTRYPOINT ["/usr/local/bin/setup-all"]'
    {{ container_name }} {{ image_namespace }}/{{ image_name }}:{{ image_tag }}

- name: Post | log into registry
  docker_login:
    registry: nexus.cci-dev.pl
    username: "{{ nexus_user }}"
    password: "{{ nexus_password }}"
    reauthorize: yes
  tags:
    - push

- name: Post | push it to repo
  docker_image:
    name: "{{ image_namespace }}/{{ image_name }}"
    push: yes
    tag: "{{ image_tag }}"
  tags:
    - push

- name: Post | add tag latest to image
  docker_image:
    name: "{{ image_namespace }}/{{ image_name }}:{{ image_tag }}"
    repository: "{{ image_namespace }}/{{ image_name }}:latest"
    force: yes
    push: yes
  tags:
    - latest

- name: Post | remove the container
  docker_container:
    name: '{{ container_name }}'
    state: absent
